name: Linux C ARM64 Build

on:
  push:
  pull_request:

jobs:
  linux-arm64-c-build:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y bc
      - name: Build BLASFEO
        run: |
          git clone https://github.com/giaf/blasfeo
          make -C blasfeo static_library TARGET=ARMV8A_ARM_CORTEX_A57 LA=HIGH_PERFORMANCE -j 4
      - name: Build HPIPM and run C tests
        run: |
          make static_library TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo -j 4
          make -C test_problems test_d_dense TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          # make -C test_problems test_d_dense_qcqp TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_ocp TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_ocp_qcqp TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_cond TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          # make -C test_problems test_d_cond_qcqp TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_part_cond TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          # make -C test_problems test_d_part_cond_qcqp TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_tree_ocp TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          # make -C test_problems test_d_tree_ocp_qcqp TARGET=GENERIC BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0