name: Linux Octave Build

on:
  push:
  pull_request:

jobs:
  linux-amd64-octave-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y octave liboctave-dev bc
      - name: Build BLASFEO
        run: |
          git clone https://github.com/giaf/blasfeo
          make -C blasfeo shared_library TARGET=X64_INTEL_HASWELL LA=HIGH_PERFORMANCE -j 4
      - name: Build HPIPM (Octave interface) and run examples
        run: |
          make shared_library TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo -j 4
          make -C interfaces/matlab_octave all -j 4
          source interfaces/matlab_octave/env.sh
          make -C examples/matlab_octave example_getting_started
          make -C examples/matlab_octave example_from_qp_data_c
          make -C examples/matlab_octave example_mass_spring
          make -C examples/matlab_octave example_mass_spring_qcqp
          make -C examples/matlab_octave example_getting_started_dense_qp
        shell: bash