name: Linux Python Build

on:
  push:
  pull_request:

jobs:
  linux-amd64-python-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y bc
      - name: Build BLASFEO
        run: |
          git clone https://github.com/giaf/blasfeo
          make -C blasfeo shared_library TARGET=X64_INTEL_HASWELL LA=HIGH_PERFORMANCE -j 4
      - name: Build HPIPM (Python interface) and run examples
        run: |
          make shared_library TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo -j 4
          make -C interfaces/python all
          make -C examples/python example_qp_getting_started
          make -C examples/python example_qcqp_getting_started
          make -C examples/casadi_python get_casadi
          make -C examples/casadi_python example_PMSM