name: Linux C AMD64 Build

on:
  push:
  pull_request:

jobs:
  linux-amd64-c-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y bc
      - name: Build BLASFEO
        run: |
          git clone https://github.com/giaf/blasfeo
          make -C blasfeo static_library TARGET=X64_INTEL_HASWELL LA=HIGH_PERFORMANCE -j 4
      - name: Build HPIPM and run C tests
        run: |
          make static_library TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo -j 4
          make -C test_problems test_d_dense TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          # make -C test_problems test_d_dense_qcqp TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_ocp TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_ocp_qcqp TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_cond TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_cond_qcqp TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_part_cond TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_part_cond_qcqp TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_tree_ocp TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0
          make -C test_problems test_d_tree_ocp_qcqp TARGET=AVX BLASFEO_PATH=${{ github.workspace }}/blasfeo PRINT=0